matrix:
    include:
        - language: node_js
          node_js: '12'
          cache:
              - yarn: true
          before_install:
              - cd frontend
          branches:
              only:
                  - addDocker
          notifications:
              - 
          install:
              - yarn install
          script:
              - ./node_modules/.bin/eslint src/
              - yarn test --coverage --watchAll=false

        - language: python
          python: '3.7'
          cache:
              - pip: true
          before_install:
              - cd backend
          branches:
              only:
                  - addDocker
          install:
              - pip install -r requirements.txt
          script:
              - pylint **/*.py --load-plugins pylint_django
              - coverage run --source='.' manage.py test
              - coverage xml

notifications:
    slack: shallwegame:El1u9YYh60IUQsdgDHHSzpQ7
